### ISSUE TITLE
你好，请问一下.npz文件在哪里呀

### ISSUE THREAD

**Issue by RenatusYin** [Burhan-Q/ClassifyDefectMap_MixedWM38#1]
`file = list(Path(".").glob("*.npz"))[0]
data = np.load(file)`没在目录里面找到这个文件

**Comment by Burhan-Q** [comment]
@RenatusYin the `.npz` file is from the dataset which I downloaded from [Kaggle](https://www.kaggle.com/datasets/co1d7era/mixedtype-wafer-defect-datasets) which I found via the GitHub repo [here](https://github.com/Junliangwangdhu/WaferMap). Once downloaded, put the `.npz` file in my working directory with my code to open the file, but you can specify the location where you save the file by replacing `Path('.')` with `Path('path/to/download.npz')`
